package com.guljar.music.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Structured result from AI image analysis.
 * Contains rich musical context extracted from the uploaded image
 * to enable highly relevant music recommendations.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ImageAnalysisResult {

    /** Primary mood/emotion detected (e.g., "melancholic", "euphoric", "peaceful") */
    private String mood;

    /** Suggested music genre (e.g., "Lo-fi", "Classical", "Indie Folk") */
    private String genre;

    /** Energy level: "low", "medium", or "high" */
    private String energy;

    /** Scene/situation description (e.g., "rainy evening in a cafe") */
    private String scene;

    /** Specific artist or song suggestions from the AI */
    private List<String> artistSuggestions;

    /** Optimized web search queries generated by the AI */
    private List<String> searchQueries;

    /** Raw comma-separated keywords (fallback, backward compatible) */
    private String rawKeywords;
}
